name: CI

on:
  pull_request:
    branches: 
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install 
    - name: Linting
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint 
    - name: Jest Tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
