# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install 
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint 
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
