name: CI

on:
  pull_request:
    branches: 
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
      - name: Linting
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint 
      - name: Jest Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
  
  cypress:
    name: Cypress Tests
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.13.2-chrome97-ff96
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          browser: chrome
